export const ADD_TASK = "ADD_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const GENERATE_NEW_ID = "GENERATE_NEW_ID";
export const TOGGLE_COMPLETE = "TOGGLE_COMPLETE";
export const DELETE_ALL_DONE_TASKS = "DELETE_ALL_DONE_TASKS";
