export const ADD_TASK = "ADD_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const TOGGLE_COMPLETE = "TOGGLE_COMPLETE";
export const DELETE_ALL_DONE_TASKS = "DELETE_ALL_DONE_TASKS";
export const SET_ALL_TASKS = "SET_ALL_TASKS";
export const SET_TASK_NAME = "SET_TASK_NAME";
